### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by VoyageWang** [weihao1115/mm-sam#3]
Hi there！

Thanks for your great work. I want to know when the code will be released?

**Comment by weihao1115** [comment]
Hi @VoyageWang ,

Thank you for your interest in our work!

We're currently finalizing the code release and expect to complete it within the next few days. Please stay tuned.

Best regards,

**Comment by weihao1115** [comment]
We have updated the code for testing. Thank you for your waiting.

Best regards,
