### ISSUE TITLE
When will the training code be released?

### ISSUE THREAD

**Issue by XiaozhenQiao** [weihao1115/mm-sam#5]
Excellent work. When will the training code be released?

**Comment by weihao1115** [comment]
Hi @XiaozhenQiao ,

Thank you for your interest in our work! We plan to release the training code upon acceptance. After acceptance, we will release the MM-SAM's training and testing code based on SAM1 and SAM2.

Best regards,

**Comment by XiaozhenQiao** [comment]
Looking forward to your code，I wish your article will be received soon.
Best wishes!
