### ISSUE TITLE
A question about pseudo labels of WMMF 

### ISSUE THREAD

**Issue by wuaodi** [weihao1115/mm-sam#8]
Very inspiring work! I have a small question about the training of WMMF. During training, the pseudo labels are sourced by _’selecting the most confident predictions from corresponding patches of the paired modalities‘._ Does this mean the training upper limit is the result of these pseudo labels? If so, could we directly fuse the results of the two modalities in the result domain to achieve multi-modal fusion output?

**Comment by weihao1115** [comment]
Hi @wuaodi ,

Thank you for this excellent question. Yes, the quality of pseudo-labels is important for the final fusion, just as in other pseudo-label learning methods. You can certainly merge the results in the output domain using various data fusion algorithms, which is perfectly fine. 

In fact, the core idea of our WMMF is to propose such an idea, demonstrating the possibility to everyone that data fusion methods can be used to refine the final results from the original RGB branch and transferred X branch under a sensor suite.

Best regards,

**Comment by wuaodi** [comment]
Thanks for your reply. I understant your idea more clearly now, and I appreciate this work soooo much!
